In [5]:
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime


In [6]:
path = 'Timg'
images = []
classNames = []
myList = os.listdir(path)
print(myList)

['Bill Gates.jpg', 'Elon.jpg', 'Uthand.JPG', 'Vathsav.JPG']


In [7]:
import cv2
for i in myList:
    curImg = cv2.imread(f'{path}/{i}')
    images.append(curImg)
    classNames.append(os.path.splitext(i)[0])
print(classNames)

['Bill Gates', 'Elon', 'Uthand', 'Vathsav']


In [8]:
def findEncodings(images):
    encodeList = []
    for img in images:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        encode = face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList


In [9]:
def markAttendance(name):
    with open('attendance.csv', 'r+') as f:
        myDataList = f.readlines()
        nameList = []
        for line in myDataList:
            entry = line.split(',')
            nameList.append(entry[0])
        if name not in nameList:
            now = datetime.now()
            dtString = now.strftime("%HH:%MM:%SS")
            f.writelines(f'\n{name},{dtString}')


In [10]:
import face_recognition
encodeListKnown = findEncodings(images)
print("encoding complete")
cap = cv2.VideoCapture(0)

while True:
    success, img = cap.read()
    imgS = cv2.resize(img, (0, 0), None, 0.25, 0.25)
    imgS = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    
    facesCurFrame = face_recognition.face_locations(imgS)
    encodesCurFrame = face_recognition.face_encodings(imgS, facesCurFrame)

    for encodeFace, faceLoc in zip(encodesCurFrame, facesCurFrame):
        matches = face_recognition.compare_faces(encodeListKnown, encodeFace)
        faceDis = face_recognition.face_distance(encodeListKnown, encodeFace)
        print(faceDis)
        matchIndex = np.argmin(faceDis)

        if matches[matchIndex]:
            name = classNames[matchIndex].upper()
            print(name)
        
            markAttendance(name)
    cv2.imshow('Webcam', img)
    cv2.waitKey(1)


encoding complete
[0.84888561 0.88636346 0.55185591 0.48217885]
VATHSAV
[0.83580703 0.90478557 0.74456023 0.54846998]
VATHSAV
[0.84874985 0.88432737 0.64312554 0.52717909]
VATHSAV
[0.86008439 0.88583342 0.570191   0.52432758]
VATHSAV
[0.78718051 0.82204678 0.59532542 0.57640469]
VATHSAV
[0.83273086 0.81239455 0.53753982 0.4631831 ]
VATHSAV
[0.83372448 0.79189501 0.5325808  0.5544988 ]
UTHAND
[0.87161817 0.87748271 0.54283045 0.48084649]
VATHSAV
[0.74320483 0.75552312 0.67557755 0.63349184]
[0.89371958 0.88524942 0.59958165 0.46018942]
VATHSAV
[0.81895621 0.72873697 0.67019545 0.66455668]
[0.85744442 0.88277681 0.63782101 0.62352386]
[0.90381539 0.8927251  0.46621629 0.66067666]
UTHAND
[0.83994373 0.8593741  0.38921971 0.65702483]
UTHAND
[0.80872874 0.85398455 0.37082738 0.65447535]
UTHAND
[0.82238166 0.77218151 0.64173516 0.65324874]
[0.80479452 0.75258068 0.66121035 0.67053618]
